# theme: jekyll-theme-slate
theme: just-the-docs
title: Zoning in the Twin Cities
description: Data, methodology and advice for others interested in replicating the Star Tribune's analysis of zoning data in the Twin Cities
show_downloads: false
