theme: jekyll-theme-slate
# remote_theme: pmarsceill/just-the-docs
title: Zoning in the Twin Cities
description: Data and methodology for others interested in replicating the Star Tribune's analysis of zoning data in the Twin Cities
show_downloads: false
